name: publish to marketplace

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: install dependencies
        run: npm install
      - name: install vsce
        run: sudo npm install -g vsce
      - name: publish into marketplace
        run: vsce publish -p ${{ secrets.TOKEN }}
